### ISSUE TITLE
Advanced use example hangs up 

### ISSUE THREAD

**Issue by LeonFon** [sbtinstruments/asyncio-mqtt#10]
The code hangs up, without any message, when an exception is occurred during log_messages execution.

`async def log_messages(messages, template):
    async for message in messages:
        print(template.format(message.payload.decode()) # if it failed to decode, because of binary data in my case it hangs up forever`

For my specific case i figured it out, but it is a dangerous.

**Comment by frederikaalund** [comment]
Thank you for reporting this issue. Let me have a look. :)

You're right, Python's `bytes.decode` function assumes that the binary represents an UTF8-encoded string per default. If the `message.payload` (`bytes`) object does not follow this assumption, `decode` will raise an exception.

Whether the MQTT message payload is UTF8-encoded text, audio data, video frames, or even empty is completely up to the application (i.e., your usage of MQTT). The asyncio-mqtt does not impose any restrictions here.

In the *example code*, I have assumed that the message payload is UTF8-encoded text. This was done to make the example code a simple *starting point* for many applications. In your case, it seems that this assumption led to headaches. Sorry about that.

I can see two options here:
 * Add a comment to the example code about the UTF8-encoded text assumption.
 * Change the example code to simply display the raw binary data (without the `bytes.decode` call). The output will be more messy like this but at least it won't make assumptions about the payload.

What do you think? Do you have a third option in mind?

**Comment by LeonFon** [comment]
Thank you for your response.

My point was more about the **exception handling**.
If any exception will occur in this block of code the code will just hang up.

Regarding the decoding, I think that adding a comment will be enough :)

Right now i implemented this in other way:

```python
async def start_mqtt_client():
    async with Client(
            hostname=config.mqtt.server) as client:

        tasks = []
        tasks.append(asyncio.create_task(handle_bcg(
            client.filtered_messages("/filter1"))))
        tasks.append(asyncio.create_task(handle_sts(
            client.filtered_messages("/filter2"))))

        await client.subscribe("/topic1")
        await client.subscribe("/topic2")
        await asyncio.gather(*tasks)
```

**Comment by frederikaalund** [comment]
Thanks for the follow-up with additional details.

> My point was more about the exception handling.
> If any exception will occur in this block of code the code will just hang up.

Ah, I see. I could reproduce this behaviour in the advanced example from README.md. I assume that your code is closely based on the advanced example.

I think that is not an issue with asyncio-mqtt itself but with the example code. Specifically, I think that I made a mistake in the `cancel_tasks` helper function.

Can you please try to apply the following change:

```python
async def cancel_tasks(tasks):
    for task in tasks:
        if task.done():  # Added
            continue     # Added
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
```

Again thanks for reporting this issue. :)

**Comment by LeonFon** [comment]
Yes, it is not an issue with the asyncio-mqtt, just in the example code.
Anyway it's handling the exception with your changes :)
So i thing you should add that change to README.md

**Comment by frederikaalund** [comment]
>Anyway it's handling the exception with your changes :)

That's great to hear. I consider this issue solved then. :)

> So i think you should add that change to README.md

Already done!
