### ISSUE TITLE
QOS1 first incoming message if missed after starting the client

### ISSUE THREAD

**Issue by Kopeika** [sbtinstruments/asyncio-mqtt#109]
Debian, Python 3.10, mosquitto as a broker

started:
mosquitto_sub --topic  /mytopic -q 1 -i myclient -c

send one message:
mosquitto_pub -f current/cache_push.json --topic  /mytopic -q 1

it will be received by mosquito_sub

now I stopped mosquitio_sub
and send one message using 
mosquitto_pub -f current/cache_push.json --topic  /mytopic -q 1

it was stored in MQTT broker

when i started 
mosquitto_sub --topic  /mytopic -q 1 -i myclient -c

I got that message.

This is ok. It must work this way.

Now i will use your updated example code instead of mosquito_sub as a client

1) i wil execute it once - so it will store client_id, and subscription information in the MQTT broker
2) i will stop client
3) i wil send message using mosquitto_pub -f current/cache_push.json --topic  /mytopic -q 1
4) i will start client 
5) no incoming messages

if i will send 3 messages instead of one at 3) - i will receive two of them. 

What am I doing wrong?

Thank you!

`
import asyncio
import logging
from asyncio_mqtt import Client, MqttError

logger = logging.getLogger(__name__)

async def tick():
    while True:
        #logger.info("Tick")
        await asyncio.sleep(1)

async def test():
    while True:
        try:
            logger.info("Connecting to MQTT")
            async with Client("localhost", client_id="minmax" , clean_session=False) as client:
                logger.info("Connection to MQTT open")
                async with client.unfiltered_messages() as messages:
                    await client.subscribe("#",1)
                    async for message in messages:
                        logger.info(
                            "Message %s %s", message.topic, message.payload.decode()
                        )
                # await asyncio.sleep(2)
        except MqttError as e:
            logger.error("Connection to MQTT closed: " + str(e))
        except Exception:
            logger.exception("Connection to MQTT closed")
        await asyncio.sleep(3)

def main():
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    asyncio.get_event_loop().run_until_complete(asyncio.wait([test(), tick()]))

if __name__ == "__main__":
    main()

`

**Comment by frederikaalund** [comment]
Hi and thanks for opening this issue. Let me have a look. :)

This sounds a lot like issue #95 to me. Try to do something like the following (taken from a comment of mine in #95):

```python
async def main():
    # Create client object (1)
    client = with Client(
        MQTTHOST,
        MQTTPORT,
        username=MQTTUSER,
        password=MQTTPWD,
        client_id=MQTTID,
        clean_session=False,
    )
    # Add message handler
    messages = client.filtered_messages("ame_test/data/#")
    # Register message handler (3) and connect the client (2)
    async with messages, client:
        await client.subscribe("ame_test/data/#", qos=1)
        async for message in messages:
            print(message.payload.decode())
```

This way, we set up the message handler *before* the client connects to the server. Let me know if this works for you. :)

~Frederik

**Comment by Kopeika** [comment]
Hello, thank you for your answer!
This works for me: (sorry for formatting)

`
   client = Client(
         'MQTTHOST,
        MQTTPORT,
        username=MQTTUSER,
        password=MQTTPWD,
        client_id=MQTTID,
        clean_session=False)

    async with client.unfiltered_messages() as messages:
        async with client:
            await client.subscribe("/test", qos=1)
            async for message in messages:
                print(message.payload.decode())

`

**Comment by frederikaalund** [comment]
I closed this issue since we already track it in #95. Let me know if something is still unclear.
