### ISSUE TITLE
Immediate disconnected after subscribe

### ISSUE THREAD

**Issue by pallas** [sbtinstruments/asyncio-mqtt#11]
I'm using the example code, which worked a few weeks ago. Now, it's sending a DISCONNECT right after a SUBACK. I don't know if asyncio-mqtt or paho.mqtt.python changed. Has anyone seen behaviour like

```
DEBUG:mqtt:Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'2c063326-vpn'
DEBUG:mqtt:Received CONNACK (0, 0)
DEBUG:mqtt:Sending SUBSCRIBE (d0, m1) [(b'prefix/+', 0)]
DEBUG:mqtt:Received SUBACK
DEBUG:mqtt:Sending DISCONNECT
```

with code like

```python
async with Client(...) as client:
    async with client.filtered_messages(f'{request_prefix}/+') as messages:
        await client.subscribe(f'{request_prefix}/+')
        async for message in messages:
            pass
```

Currently, it never makes it into the innermost loop.

**Comment by pallas** [comment]
Ok, I figured it out.. it's a python 3.6 issue, see PR #12.

**Comment by frederikaalund** [comment]
I figure that now that #12 is merged, this issue is solved too, right? If not, then just let me know and I will try to investigate.

**Comment by pallas** [comment]
That's correct
