### ISSUE TITLE
mqtt over TLS

### ISSUE THREAD

**Issue by bbartling** [sbtinstruments/asyncio-mqtt#111]
Hi, does this library support mqtt over TLS? x-509

**Comment by frederikaalund** [comment]
Hi Bent, thanks for opening this issue. Let me have a look. :)

Yes, via the `tls_context` argument to `Client.__init__`. See [python's built-in `ssl.SslContext` class](https://docs.python.org/3/library/ssl.html#ssl-contexts) for additional details.

I have no personal experience with `ssl.SslContext` so I can't really provide an example. We simply forward said context to the [underlying paho MQTT client via `tls_set_context`](https://github.com/eclipse/paho.mqtt.python#tls_set_context).

I hope that helps. 👍 I can see that I missed the discussion that you created here in this repo. Sorry about that.

~Frederik

**Comment by bbartling** [comment]
Thanks! This is a very slow side project for me if I can get the TLS to work ill post something maybe to use as an example.

**Comment by ser** [comment]
for me with a valid cert works this:

``transport='websockets', port=443, tls_context=ssl.create_default_context()``

IMHO it should arrive to documentations how to create default context.

**Comment by buhln** [comment]
Here a working example with a self-signed certificate `ca.pem`:

```python
import asyncio
import aiomqtt
import ssl

async def main():
    tls_params = aiomqtt.TLSParameters(
        ca_certs='./ca.pem',
        certfile=None,
        keyfile=None,
        cert_reqs=ssl.CERT_REQUIRED,
        tls_version=ssl.PROTOCOL_TLS,
        ciphers=None,
    )
    async with aiomqtt.Client("test.mosquitto.org", tls_params=tls_params) as client:
        await client.publish("test/test", payload=28.4)

if __name__ == "__main__":
    asyncio.run(main())
```
