### ISSUE TITLE
Payload missing when subscribing to persistent messages with clean_session=False

### ISSUE THREAD

**Issue by anudeep010291** [sbtinstruments/asyncio-mqtt#112]
**Mosquitto version :** 1.6.4
**MQTT protocol :** v3.1
**Environment :** Ubuntu 18.04.5 LTS bionic

- A publisher(synchronous) publishes messages every 1 sec to a particular topic(test) with qos=1 and the subscriber listening to the same topic(test) is down for a period of 30 mins with clean session=False and qos=1.
- Once the subscriber is up we could see the messages that was received during the 30 mins the subscriber was down.
- But when analyzing the messages we could see some of the data in between are missing for a period of time though the missing messages were published.
- The below asynchronous subscriber code has been to suscribe the messages.

```import asyncio
import json
from asyncio_mqtt import Client

hostname = "127.0.0.1"
client_id = "mqtt-async1"


async def mqtt_subscribe_asnyc(queue):
    async with Client(hostname=hostname, clean_session=True, client_id=client_id) as client:
        async with client.filtered_messages("/test") as messages:
            await client.subscribe("/test", qos=1)
            async for message in messages:
                await send_to_stream(message)


async def send_to_stream(message):
    try:
        payload = json.loads(message.payload)
        print(payload)
    except TypeError as e:
        print("error parsing")


async def main():
    queue = asyncio.Queue()
    tasks = set()
    f1 = loop.create_task(mqtt_subscribe_asnyc(queue))
    tasks.add(f1)
    await asyncio.gather(*tasks)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by frederikaalund** [comment]
Hi anudeep010291, thanks for opening this issue. Let me have a look. :)

This is a [known limitation of the underlying paho-mqtt library](https://github.com/eclipse/paho.mqtt.python#known-limitations). From their documentation:

> Known limitations
> The following are the known unimplemented MQTT feature.
> When clean_session is False, the session is only stored in memory not persisted. This means that when client is restarted (not just reconnected, the object is recreated usually because the program was restarted) the session is lost. This result in possible message lost.

Since asyncio-mqtt builds on top of paho-mqtt, we inherit this limitation. The only solution is to use another library. Sorry about that.

~Frederik
