### ISSUE TITLE
Connection Timeout with Context Manager

### ISSUE THREAD

**Issue by robin-blanchard** [sbtinstruments/asyncio-mqtt#116]
The `connect` method does provide a `timeout` argument. But the `__aenter__` method doesn't. So connecting to an unnexisting MQTT broker will make the context manager hang.  
A simple solution would be to be able to create the `Client` object with a default timeout to be used in the `__aenter__` method.

What do you think ?

**Comment by frederikaalund** [comment]
Hi Robin, thanks for opening this issue. :+1: 

> The connect method does provide a timeout argument. But the __aenter__ method doesn't. So connecting to an unnexisting MQTT broker will make the context manager hang.

That's a good point! It's an oversight in the API design. Sorry about that.

> A simple solution would be to be able to create the Client object with a default timeout to be used in the __aenter__ method.

Yes, that sounds like a good approach. I'd accept a PR that follows this approach. :)

~Frederik

**Comment by robin-blanchard** [comment]
Hello Frederik,

Great to hear that, I'll be happy to make these changes as soon as I have the time.

I also noticed that if I wrap the `Client` context manager in a `try/catch`, I do catch a `ConnectionError`. I'll try to see what's happening
