### ISSUE TITLE
Provide same utility and simplicity without context manager

### ISSUE THREAD

**Issue by robin-blanchard** [sbtinstruments/asyncio-mqtt#117]
Hello!

I am building a library around many asyncio connectors. And the structure I've chosen made me prefer to use connectors that I can connect and disconnect at different places in my code. This choice prevents me from easily using `asyncio-mqtt.Client` context manager.  
While the `__aenter__` method can easily be replaced by `.connect()`, the `__aexit__` provides much more functionality than the `.disconnect()` method. 
Would it be okay to wrap the content of the `__aexit__` method inside a new method ? Possibly naming it `disconnect` and renaming the current `disconnect` by `gracefully_disconnect` ?

**Comment by frederikaalund** [comment]
Hi Robin, thanks for opening this issue. :)

I understand your trouble with this whole context manager thing. It is a paradigm shift compared to a `connect`/`disconnect` function pair. It can be difficult to mix the two paradigms. That's what you're experiencing here.

Long story short, it was an API design mistake on my part to expose `connect`/`disconnect`/`force_disconnect` in the first place. With that in mind, I personally vote against a new `gracefully_disconnect` function. There is already enough confusion with the existing `disconnect`/`force_disconnect`. I'd rather remove all these functions and rely solely on the context manager semantics. Unfortunately, it's a little too late now for a breaking API change. That's on me.

---

As a workaround, you can call `__aenter__` and `__aexit__` directly. E.g.:

```python
await client.__aenter__()  # connect
...
await client.__aexit__(None, None, None)  # workaround
```

Moreover, you can create a small wrapper around `asycio_mqtt.Client` that does just that:

```python
class RobinsClient(asyncio_mqtt.Client):
    async def smart_disconnect(self) -> None:
        # HACK: We use the existing disconnect logic in asyncio-mqtt with
        # a direct call to `__aexit__`. This may break if asyncio-mqtt changes the implementation
        # of `__aexit__`. Make sure to check that whenever you upgrade the version of asyncio-mqtt.
        await self.__aexit__(None, None, None)
```

**Comment by robin-blanchard** [comment]
Hello Frederik,

Thanks for your quick reply.
I understand and agree on the fact that there is already confusion with `disconnect`/`force_disconnect`.

I indeed was planning on using the `__aexit__` method directly, thank you for your help !

**Comment by couling** [comment]
Might it be worth including a note in the documentation referring to [AsyncExitStack](https://docs.python.org/3/library/contextlib.html#contextlib.AsyncExitStack) as the proffered way to make the idiomatic switch over directly calling `__aenter__` and `__aexit__`.  This ensures that there is always a 1:1 between the two.

I personally find the the decision to go with context manager only very awkward to work with. It conflicts with the fact that context managers are designed to manage a single code path while an MQTT client will commonly have two (a producer and a consumer) and these two would usually be separate tasks.
