### ISSUE TITLE
[Question][Newbie] WARNING - There are 11 pending publish calls.

### ISSUE THREAD

**Issue by marverix** [sbtinstruments/asyncio-mqtt#119]
Hello,
I wrote a little service using your library. I'm sending around 12 messages every 3 seconds. I'm getting all the time "WARNING - There are X pending publish calls.". Is there any way to fix it? I thought that publishing is a simple TCP call, so it should take matter of milliseconds?

**Comment by frederikaalund** [comment]
Thanks for opening this issue. Have a look at: https://github.com/sbtinstruments/asyncio-mqtt/issues/29#issuecomment-752952013

Usually, this warning is just that: A warning. You can disable it if you know that the system gets time to process the calls later. E.g., if you make ~15 rapid requests in a batch and then wait a while before repeating the batch.

**Comment by skewty** [comment]
Can you please make `self._pending_calls_threshold` a settable property for the next version?

**Comment by frederikaalund** [comment]
> Can you please make `self._pending_calls_threshold` a settable property for the next version?

That's a good idea. :+1:  I'd gladly review a PR on that. :) It's a good, self-contained feature for a first contribution.
