### ISSUE TITLE
how to receive message in a limited time window?

### ISSUE THREAD

**Issue by yunfan** [sbtinstruments/asyncio-mqtt#13]
hi, there's a logic reason which made me need to check some message(like server response) in a limited time window(like 10 seconds?) . i havnt seen that support in the library, is it possible to do some hack for such feature?

**Comment by frederikaalund** [comment]
Hi yunfan. :) Thanks for raising this issue. Let me have a look.

> in a limited time window(like 10 seconds?)

Do you mean with a timeout? That is definitely possible. Both `connect`, `subscribe`, `publish`, etc. has a keyword argument called `timeout` (the default is actually 10 seconds).

So you can do something like:

```python
await client.publish("my/topic", "This is the message", timeout=5)  # 5 second timeout
```

Let me know if that solves this issue. Otherwise, please clarify a bit by adding some details. A code example would help.

~Frederik

**Comment by yunfan** [comment]
@frederikaalund  thanks for the reply, it made me understand this library deeper, but i noticed that you havnt mentioned `receiving message`,  in many use case, both side over the mqtt tunnal acts like a rpc server, when one need to publish message to another, its a rpc request which need to receive reply in a limited time, its not like the qos option.

i want to know how to impl this logic using the library . thanks again :D

**Comment by frederikaalund** [comment]
Glad I could help. :)

You can receive messages by subscribing to a topic like so:

```python
async with Client("test.mosquitto.org") as client:
    async with client.filtered_messages("floors/+/humidity") as messages:
        await client.subscribe("floors/#")
        async for message in messages:
            print(message.payload.decode())
```

Note that asyncio-mqtt only handles the message communication. That is, asyncio-mqtt does not provide high-level functionality like RPC. This is per design. Sorry to disappoint.

It sounds like an interesting project to implement RPC on top of asyncio-mqtt. Maybe you can do that in your own project? :) [You're not alone, and it is indeed possible to do RPC over MQTT (albeit a little quirky)](https://iot.stackexchange.com/questions/2097/is-there-a-standardized-rpc-mechanism-for-mqtt). Maybe you can use [the new MQTT v5 feature "Request Response"](https://www.hivemq.com/blog/mqtt5-essentials-part9-request-response-pattern/) to do this.

I hope that helps. Again, I can't support you with application-level logic like RPC. My capacity here is to help you with issues regarding asyncio-mqtt itself. If you encounter an API quirk or bug while building RPC on top of asyncio-mqtt then feel free to open a new issue. I'm going to close this one for now. :)

**Comment by yunfan** [comment]
@frederikaalund  i had found that the timeout methods like `move_on_after` from `anyio` https://anyio.readthedocs.io/en/stable/cancellation.html   could be used with message iterator, but i am not sure if it will caused message losting when the timeout condition had been triggered and a message were handled inside the library(i mean asyncio-mqtt)
