### ISSUE TITLE
ERROR Connection to MQTT closed: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by omidfathi** [sbtinstruments/asyncio-mqtt#136]
Hi,
I used paho mqtt before and have no problem with the connection, but now I need asynchronous mqtt and use asyncio-mqtt but I get these errors:

```error
DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(asyncio.wait([test()]))
2022-10-16 16:29:19 DEBUG Using proactor: IocpProactor
2022-10-16 16:29:19 INFO Connecting to MQTT
2022-10-16 16:29:19 ERROR Connection to MQTT closed: [Errno 11001] getaddrinfo failed
2022-10-16 16:29:22 INFO Connecting to MQTT
2022-10-16 16:29:22 ERROR Connection to MQTT closed: [Errno 11001] getaddrinfo failed
```

```python
import asyncio
import logging

from asyncio_mqtt import Client, MqttError, ProtocolVersion

logger = logging.getLogger(__name__)

async def test() -> None:
    while True:
        try:
            logger.info("Connecting to MQTT")
            async with Client(hostname="mqtt://192.168.1.51", port=1883) as client:
                logger.info("Connection to MQTT open")
                async with client.unfiltered_messages() as messages:
                    await client.subscribe("TimeSync")
                    async for message in messages:
                        logger.info(
                            "Message %s %s", message.topic, message.payload.decode()
                        )
                # await asyncio.sleep(2)
        except MqttError as e:
            logger.error("Connection to MQTT closed: " + str(e))
        except Exception:
            logger.exception("Connection to MQTT closed")
        await asyncio.sleep(3)


def main() -> None:
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    asyncio.get_event_loop().run_until_complete(asyncio.wait([test()]))


if __name__ == "__main__":
    main()
```

**Comment by empicano** [comment]
Hi there omidfathi,

Your issue is related to the client configuration. Try replacing the hostname with `test.mosquitto.org`, then it works. In any case, this is not related to asyncio-mqtt, you'd get the same error using paho.mqtt.

Maybe these issues help: eclipse/paho.mqtt.python#243 eclipse/paho.mqtt.python#316

**Comment by frederikaalund** [comment]
In addition, make sure that you use the `SelectorEventLoop` and *not* the `ProactorEventLoop` if you are on Windows. 👍

**Comment by omidfathi** [comment]
> Hi there omidfathi,
> 
> Your issue is related to the client configuration. Try replacing the hostname with `test.mosquitto.org`, then it works. In any case, this is not related to asyncio-mqtt, you'd get the same error using paho.mqtt.
> 
> Maybe these issues help: [eclipse/paho.mqtt.python#243](https://github.com/eclipse/paho.mqtt.python/issues/243) [eclipse/paho.mqtt.python#316](https://github.com/eclipse/paho.mqtt.python/issues/316)

Hi,
The problem is that I should connect to a broker that is run on my colleague's pc, so only thing that i have is broker ip.

**Comment by frederikaalund** [comment]
Thanks for the follow-up. :+1:

Like empicano pointed out, this sounds like an issue with your local network setup and *not* like an issue within asyncio-mqtt.

Next steps: Try to root cause the issue. Does it work when you use a local MQTT server? Does it work when you use a test MQTT server (e.g., "test.mosquitto.org")? We want to figure out on "which end of the cable" that the error occurs.

Also, are you on Windows? Because I see references to the `ProactorEventLoop` in your log messages, and asyncio-mqtt does not work with said event loop.

**Comment by omidfathi** [comment]
> In addition, make sure that you use the `SelectorEventLoop` and _not_ the `ProactorEventLoop` if you are on Windows. 👍

Thank you, the problem is solved.
I'm on Windows

> Thanks for the follow-up. 👍
> 
> Like empicano pointed out, this sounds like an issue with your local network setup and _not_ like an issue within asyncio-mqtt.
> 
> Next steps: Try to root cause the issue. Does it work when you use a local MQTT server? Does it work when you use a test MQTT server (e.g., "test.mosquitto.org")? We want to figure out on "which end of the cable" that the error occurs.
> 
> Also, are you on Windows? Because I see references to the `ProactorEventLoop` in your log messages, and asyncio-mqtt does not work with said event loop.

Thank you, the problem is solved.
I'm on Windows and use `SelectorEventLoop`, now I have no connecting problem.

**Comment by omidfathi** [comment]
my new problem is my code block on this line:
```python
async for message in messages:
```
and stay frozen and do nothing.

**Comment by frederikaalund** [comment]
Glad to help. :+1: 



> my new problem is my code block on this line:
> 
> ```python
> async for message in messages:
> ```
> 
> and stay frozen and do nothing.

This code stays "frozen" until it receives a message. Did you try to send a message to the server? If not, try to do so. E.g., with a local, CLI-based MQTT client or similar.

**Comment by omidfathi** [comment]
> Glad to help. 👍
> 
> > my new problem is my code block on this line:
> > ```python
> > async for message in messages:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and stay frozen and do nothing.
> 
> This code stays "frozen" until it receives a message. Did you try to send a message to the server? If not, try to do so. E.g., with a local, CLI-based MQTT client or similar.

The topic that I subscribed (TimeSync), always publishes time in bytes to the broker for syncing between devices.

**Comment by omidfathi** [comment]
> > Glad to help. 👍
> > > my new problem is my code block on this line:
> > > ```python
> > > async for message in messages:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and stay frozen and do nothing.
> > 
> > 
> > This code stays "frozen" until it receives a message. Did you try to send a message to the server? If not, try to do so. E.g., with a local, CLI-based MQTT client or similar.
> 
> The topic that I subscribed (TimeSync), always publishes time in bytes to the broker for syncing between devices.
The problem was decoding, we publish data on the broker in Bytes. I should first receive data in bytes and then decode by custom byte structure.
