### ISSUE TITLE
Windows 10 Pro error, Python 3.8: add_reader NotImplemented? FYI: this project isn't async.

### ISSUE THREAD

**Issue by robertsdotpm** [sbtinstruments/asyncio-mqtt#139]
On Windows 10 with Python 3.8 I get the following error trying to use the software. It complains about 'add_reader' not being implemented for the loop object. Checking in a terminal I see that these functions are available and fine. Digging into the code some more... I am surprised to see that regular blocking sockets are used for the I/O? This project describes itself as being an asyncio MQTT client. **This is not async I/O**, it's blocking sockets, even if you strap on a process pool executor to avoid locking the main thread you're still avoiding the benefits of using asynchronous IO. 

I should have looked closer at the code before I used it. As I've avoided using all blocking code until now. Chances are high that if this were written with modern asyncio events it would have less errors. Since the asyncio code has been well tested across platforms. I will have to see if there's any alternatives that are async now because I don't have time to fix this.

```
"c:\python\lib\site-packages\asyncio_mqtt\client.py", line 222, in connect
    await loop.run_in_executor(
  File "c:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python\lib\site-packages\paho\mqtt\client.py", line 914, in connect
    return self.reconnect()
  File "c:\python\lib\site-packages\paho\mqtt\client.py", line 1086, in reconnect
    self._call_socket_open()
  File "c:\python\lib\site-packages\paho\mqtt\client.py", line 2155, in _call_socket_open
    on_socket_open(self, self._userdata, self._sock)
  File "c:\python\lib\site-packages\asyncio_mqtt\client.py", line 520, in _on_socket_open
    self._loop.add_reader(sock.fileno(), cb)
  File "c:\python\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
```

**Comment by frederikaalund** [comment]
See https://github.com/sbtinstruments/asyncio-mqtt#note-for-windows-users

Let me know if this fixes the issue for you or not. 👍

**Comment by robertsdotpm** [comment]
Hello @frederikaalund, thanks for providing support and maintenance for this project. I know it's open source and volunteer so I appreciate it. This info is very useful. I couldn't find any solid info about this even on Google so this is probably going to help even unrelated projects, too. Thank you.
