### ISSUE TITLE
Add CI to format, lint, test, coverage and publish

### ISSUE THREAD

**Issue by JonathanPlasse** [sbtinstruments/asyncio-mqtt#143]
This would add more reliability to the project.

**Comment by frederikaalund** [comment]
I agree to all of the proposed tools. 👍

Do you have a specific CI pipeline in mind? Being open source, we usually get compute hours for free.

**Comment by JonathanPlasse** [comment]
- Github actions to test and publish
- Codecov for coverage
- pre-commit.ci to format and lint

**Comment by frederikaalund** [comment]
Good choices. 👍 

> pre-commit.ci to format and lint

That's a new one for me. Let's try it. :)

**Comment by empicano** [comment]
Great idea! For code coverage, I once used [CodeClimate](https://codeclimate.com/quality) for another project. That analyzes code quality as well. Just throwing that out there, I have no preference.

**Comment by JonathanPlasse** [comment]
For the tests, I was thinking of using AnyIO. It makes for cleaner tests. If we transition to using AnyIO internally, the tests would not have to be rewritten.

**Comment by frederikaalund** [comment]
I think that it's a good idea to use anyio. :)

By coincidence, I'm currently writing some anyio-based pytests right now for another project. 😄

**Comment by frederikaalund** [comment]
For your information, I'll be AFK the rest of the day.

I like the progress so far! 👍

**Comment by JonathanPlasse** [comment]
Reference to publish a release [How to Publish a Python Package from GitHub Actions](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/)

**Comment by frederikaalund** [comment]
> Reference to publish a release [How to Publish a Python Package from GitHub Actions](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/)

Would be sweet to set this up! It's a bit cumbersome for me to do it manually via twine right now. 😄 

If you guys (@JonathanPlasse and @empicano ) have a PyPI account then I can add you as maintainers there as well. That way, you can publish releases too. 👍

**Comment by JonathanPlasse** [comment]
My PyPI username is `JonathanPlasse`

**Comment by empicano** [comment]
Mine is `empicano` 😊

**Comment by frederikaalund** [comment]
Thanks, I added you both. :+1: 

I'll try to get some time to go over the PRs later.

**Comment by JonathanPlasse** [comment]
@frederikaalund, can you add the PYPI_API_TOKEN in the repository secrets (c.f. [link](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/#create-a-pypi-api-token))

**Comment by frederikaalund** [comment]
> @frederikaalund, can you add the PYPI_API_TOKEN in the repository secrets (c.f. [link](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/#create-a-pypi-api-token))

Done. :+1:

**Comment by JonathanPlasse** [comment]
@frederikaalund, can you remove the tag `v0.14.0`? The publishing did not work as my email address was not considered valid.

**Comment by frederikaalund** [comment]
> @frederikaalund, can you remove the tag v0.14.0? The publishing did not work as my email address was not considered valid.

Done. :)

**Comment by JonathanPlasse** [comment]
The CI to publish is failing over some incorrect metadata.
I do not have time to go over it.
I would gladly hand it over to whoever wants to fix it.

**Comment by frederikaalund** [comment]
I'll try to get it to work this weekend. :)

**Comment by frederikaalund** [comment]
I just ran the "Publish" job again (without any changes on my part) and it worked flawlessly. 😄 Version 0.14.0 appeared immediately on PyPI. I guess it was just a fluke before. Maybe it took some time for you guys' PyPI credentials/API keys/secrets/etc. to work their way through the systems.

Good job @JonathanPlasse with these CI-related features. 👍 It really helps with the maintenance burden.

Off topic: We just hit 200 GitHub stars! ⭐

**Comment by empicano** [comment]
> Off topic: We just hit 200 GitHub stars! ⭐

<img width=260 src="https://media2.giphy.com/media/IwAZ6dvvvaTtdI8SD5/giphy.gif?cid=ecf05e476gr0i5yuahwa3semom6m88wcf0itb3hgp1aqyozg&rid=giphy.gif" />
