### ISSUE TITLE
Newbie question: initialize client

### ISSUE THREAD

**Issue by ShieldTrade** [sbtinstruments/asyncio-mqtt#156]
Hi, I am a newbie getting familiar with your library.

Following your Configuring the client example I notice the following:
1) `import paho.mqtt as mqtt` I think it should be `import paho.mqtt.client as mqtt`

2) when passing arguments 
```
aiomqtt.Client(
                        ....................
                       clean_start=mqtt.Client.MQTT_CLEAN_START_FIRST_ONLY
                         )
```
but `MQTT_CLEAN_START_FIRST_ONLY` is not a valid attribute. this might be related to this open issue [552](https://github.com/eclipse/paho.mqtt.python/issues/442)

thankyou

**Comment by empicano** [comment]
Hi there,

Thanks for opening this issue 👍 

I'm not sure I'm following you. In your code `mqtt.Client.MQTT_CLEAN_START_FIRST_ONLY` should be `mqtt.client.MQTT_CLEAN_START_FIRST_ONLY`. Maybe that does already solve your issue?

If not, could you paste the full exception trace you're getting?

**Comment by ShieldTrade** [comment]
You are right. Issue number 1 is solved. what about number 2

tx

**Comment by empicano** [comment]
Please paste the full exception trace you're getting.

**Comment by empicano** [comment]
I'll close this as there have been no more responses. If there's anything left unclear, feel free to reopen!
