### ISSUE TITLE
Add possibility to setup client clean_session=False

### ISSUE THREAD

**Issue by madnadyka** [sbtinstruments/asyncio-mqtt#16]
Add possibility to setup client clean_session=False

**Comment by frederikaalund** [comment]
Thanks for submitting this issue. Let me have a look. :)

That's indeed a key piece of MQTT functionality that paho support and asyncio-mqtt currently doesn't. Good idea to add it to asyncio-mqtt. I think that it is best implemented as a keyword argument (`clean_session`) to the `Client` constructor.

Do you want to make a pull request or should I just go ahead and add this?

**Comment by madnadyka** [comment]
I have created pull request, please check.

**Comment by frederikaalund** [comment]
Thanks for the pull request. :) It is merged now. Let me know if you run into other issues.
