### ISSUE TITLE
'Listening without blocking' on README should be changed or at least add a warning

### ISSUE THREAD

**Issue by grvstick** [sbtinstruments/asyncio-mqtt#160]
Hello,

 First of all I want to thank all the maintainers for this project, I'm heavily relying on "asyncio-mqtt" for my projects at my work.
It's been a while since I visited the github page and I was glad to see all the changes in the README file, so I took some time to read all of them.

 However, I found just one thing that looks awry, or 'possibly misleading'. Take a look at this code in the README page.

```import asyncio
import asyncio_mqtt as aiomqtt


async def listen():
    async with aiomqtt.Client("test.mosquitto.org") as client:
        async with client.messages() as messages:
            await client.subscribe("humidity/#")
            async for message in messages:
                print(message.payload)


async def main():
    # Wait for messages in (unawaited) asyncio task
    loop = asyncio.get_event_loop()
    task = loop.create_task(listen())
    # This will still run!
    print("Magic!")
    # If you don't await the task here the program will simply finish.
    # However, if you're using an async web framework you usually don't have to await
    # the task, as the framework runs in an endless loop.
    await task


asyncio.run(main())
```

In asyncio, it is generally a good practice to 'await' for every tasks that has been created. It is because only tasks that are awaited would let the programmer know that an exception, which has not been catched, is raised from that task.

Take this code example,
```import asyncio

async def error_coro():
    await asyncio.sleep(1)
    print("RAISING ERROR!")
    raise ZeroDivisionError


async def main(await_error_task: bool = False):
    error_task = asyncio.create_task(error_coro())
    if await_error_task:
        await error_task
    else:
        # error task will be silent until the program finishes, which is not desirable in most cases
        await asyncio.sleep(5)


asyncio.run(main())
```

if you do `asyncio.run(main(True))`, the exception is immediately propagated to the main() coroutine when it was raised, whereas it does not when it is `asyncio.run(main())`

In some cases you want to do 'fire-and-forget' but python official docs says to always add a `add_done_callback` for such tasks.
https://docs.python.org/3/library/asyncio-task.html#creating-tasks

**Comment by empicano** [comment]
Hi there,

Thank you for opening this well-thought-out issue! 👍 (And thank you for noticing the changes to the `README`!)

If I understand you correctly, the part that might be misleading is this comment:

```python
    # However, if you're using an async web framework you usually don't have to await
    # the task, as the framework runs in an endless loop.
```

The idea of this section and the comment was indeed to show how to implement a fire-and-forget listener. If you want to run a web server _and_ listen to MQTT messages at the same time, fire-and-forget is essentially the only option you have.

As you say, any exceptions inside tasks are only handled once we `await` them. If we don't, we'll see the exception only when the program finishes. That means that we have to handle every possible exception _inside_ a fire-and-forget task.

---

On re-reading the section, you're definitely right that it could still be improved. You have a good point about needing to add an `add_done_callback` to fire-and-forget tasks as well. 👍 

So, ideas for improvement:

- add a note about `add_done_callback`
- explain that exceptions will only be handled once we await the task -> for fire-and-forget tasks, all exceptions thus need to be handled inside the task
- maybe also add an explanation of how to properly cancel a fire-and-forget task?
- make the example more specific for use with web frameworks? Or are there other use cases for fire-and-forget with this library?

What do you think? Do you have any concrete ideas what we could add or change to make that section clearer? 😊

**Comment by grvstick** [comment]
It is too bad that TaskGroups came into play only just now in python 3.11

> add a note about add_done_callback
> explain that exceptions will only be handled once we await the task -> for fire-and-forget tasks, all exceptions thus need to be handled inside the task

I think these are the best choices for web frameworks I guess. May be add one line more...

"If you are not using a web framework, use asyncio.gather or asyncio.TaskGroup to run your task along with asyncio-mqtt."

**Comment by empicano** [comment]
I just updated the "Listening without blocking" section in the documentation.

What do you think, does that make it clearer? Is anything still missing? 😊
