### ISSUE TITLE
messages() does not have fields like properties, as does the filtered_messages()

### ISSUE THREAD

**Issue by thesems** [sbtinstruments/asyncio-mqtt#163]
Hello everyone! Thank for your work on the project.

I have received a message:
"client::filtered_messages:481: filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead."

I was going to replace with the messages() but the return type Message of messages() is a subset of the original MQTTMessage.
For me, it's important to have the properties field.

I would be also open to contributing this improvement, unless it's already implemented and I missed it.

Best regards.

**Comment by empicano** [comment]
Hi there,

Thanks for opening this issue. The switch from `(un)filtered_messages` to `messages` is a big change, sorry for breaking things!

> I would be also open to contributing this improvement

Go for it! 😎

**Comment by JonathanPlasse** [comment]
The release [v0.16.0](https://github.com/sbtinstruments/asyncio-mqtt/releases/tag/v0.16.0) is out, which adds `properties` to `messages()`

**Comment by thesems** [comment]
I could not find the additions in the v0.16.0. I tried both the .zip and the pypi. Can you double-check please if it's included? Thank you.
