### ISSUE TITLE
Rename branch master to main

### ISSUE THREAD

**Issue by JonathanPlasse** [sbtinstruments/asyncio-mqtt#165]
@frederikaalund, @empicano

Here are the instructions to rename `master` to `main.`

- [x] Add `main` branch.
- [x] Set `main` as the default branch (@frederikaalund, only you can do it).
- [ ] Delete the `master` branch.
    ```shell
    git push origin --delete master
    ```
- [ ] Rename locally `master` by `main`.
    ```shell
    # Switch to the "master" branch:
    git checkout master

    # Rename it to "main":
    git branch -m master main

    # Get the latest commits (and branches!) from the remote:
    git fetch

    # Remove the existing tracking connection with "origin/master":
    git branch --unset-upstream

    # Create a new tracking connection with the new "origin/main" branch:
    git branch -u origin/main
    ```

Here is a [link](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main) that explains how to do it.

**Comment by frederikaalund** [comment]
> Set main as the default branch (@frederikaalund, only you can do it).

Done! Good initiative. 👍

**Comment by JonathanPlasse** [comment]
If I delete `master`, the current pull request will be closed.
They will have to be reopened on `main`.

**Comment by empicano** [comment]
Done 👍 I rebased my Sphinx PR from master to main as well.

**Comment by JonathanPlasse** [comment]
Is everyone ready for the deletion of `master`?

**Comment by frederikaalund** [comment]
Yes

**Comment by empicano** [comment]
Yes

**Comment by JonathanPlasse** [comment]
Done! :tada:
