### ISSUE TITLE
Client._on_socket_register_write() may deadlock

### ISSUE THREAD

**Issue by mmmspatz** [sbtinstruments/asyncio-mqtt#174]
Oops, I introduced a bug in #170. Sorry.

`Client._on_socket_register_write()` is indeed called from an executor thread at startup, and needs to interact with the main event loop in a thread-safe matter. But later, it is also called from within the event loop (I believe regularly as data is sent on the socket). 

When called from `self._loop`, the following code will deadlock:
``` python
 fut = asyncio.run_coroutine_threadsafe(on_loop_coroutine(), self._loop)
 fut.result()
```

Waiting on `fut` prevents control from being returned to the event loop, so `on_loop_coroutine()` never runs, so `fut` never becomes ready.

**Comment by mmmspatz** [comment]
Two options:
1. Delete the wait on `fut.result()`. This leaves us needlessly calling `run_coroutine_threadsafe` on the event loop we're already in most of the time.
2. Detect whether `run_coroutine_threadsafe()` is  being called from `self._loop` or not, and act accordingly. Something like this:
``` python
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop is self._loop:
            self._loop.add_writer(sock, callback)
        else:
            async def on_loop_coroutine() -> None:
                self._loop.add_writer(sock, callback)

            fut = asyncio.run_coroutine_threadsafe(on_loop_coroutine(), self._loop)
            fut.result()
```

I am not sure which one is better.

**Comment by mmmspatz** [comment]
for reference, the implmentation of `asynco.run_coroutine_threadsafe()` is [here](https://github.com/python/cpython/blob/4cc63e0d4e4cf3299dcc0ea81616ba072ae5589d/Lib/asyncio/tasks.py#L910)

It creates a Task on the loop,  and chains a `concurrent.futures.Future` to the completion of that task.

**Comment by frederikaalund** [comment]
Good point. I was a bit unsure about the `fut.result()` part in the original PR but I thought "it seems to work okay, so why not". :)

**I vote for the first option. That was the previous behaviour (fire and forget).** Do you want to do a PR?

The second option is arguably "better" but we don't have the rigorous tests to verify that it works. PRs are welcome on that front. 😄
