### ISSUE TITLE
Question: how would I change the message filter?

### ISSUE THREAD

**Issue by dr-froehlich** [sbtinstruments/asyncio-mqtt#18]

**Comment by frederikaalund** [comment]
Hi Peter

Thanks for raising this issue. Let me have a look.

> Question: is there a way I can change the topic of the messages in the filtered message logger after the task has been created. 

No, once you call `async with client.filtered_messages(topic) as messages`, you're stuck with the chosen topic for the duration of the context manager.

> If not, should I cancel this task and recreate it to do that?

That should definitely do the trick.

Do note that there is also `client.unfiltered_messages`, which you can use to get all messages regardless if the topic. In turn, you can then apply your own (dynamic) message filtering. Maybe this better suits your use case?

Let me know if you have any other issues with asyncio-mqtt.

**Comment by dr-froehlich** [comment]
Hi Frederick,

wow that was quick! Thank you for the answer. I may come back to your offer for more help :-) For now I think I am good. I had not realized that a task is generated for each topic, so my question was actually based on a wrong understanding. I will now create a message logger for each main topic so I am sorting the type of events as they come in. 

I was looking for an MQTT implementation that is based on asyncio, and yours seems to be the most advanced and current - thank you for that!

Peter

**Comment by frederikaalund** [comment]
Ah, that makes sense. In any case, I'm glad it worked out.

Please raise any issues that you experience with asyncio-mqtt. I hope to release a stable version soon and I want any obvious bugs ironed out first. :)
