### ISSUE TITLE
How to exit waiting for messages after 5 minutes?

### ISSUE THREAD

**Issue by abbazs** [sbtinstruments/asyncio-mqtt#183]
```
        async with client.filtered_messages("#") as messages:
            await client.subscribe("#")
            async for message in messages:
                print(message.payload)
```
I need to exit the `async for message in messages` loop after 5 minutes. How can I do it?

**Comment by empicano** [comment]
Hi there, great question!

The easiest way would be to do this from inside the message generator. However, the execution always blocks until a new message comes in.

## First option

If you don't need to have the task end _exactly_ after 5 minutes, you could just check if your limit is already reached each time a message comes in. When a message comes in after the limit has passed, you throw it away (to only process messages _inside_ the 5-minute limit), and `break` out of the loop.

Here's a minimal working example (with a 5 second limit):

```python
import asyncio
import asyncio_mqtt as aiomqtt
import time


timestamp = time.time()


async def main():
    async with aiomqtt.Client("test.mosquitto.org") as client:
        async with client.messages() as messages:
            await client.subscribe("humidity/#")
            async for message in messages:
                if time.time() - timestamp > 5:
                    break
                # The message that triggered the break is not printed
                print(message.payload)


asyncio.run(main())
```

## Second option

If you need your task to end exactly after 5 minutes, I don't think it's possible to do this from inside the task. I'd suggest doing it by canceling the task after the time is up.

Python 3.11 added a neat feature that you can use for this, [called timeouts](https://docs.python.org/3/library/asyncio-task.html#timeouts). Here's a minimal working example that listens for 5 seconds, then cancels the task.

```python
import asyncio
import asyncio_mqtt as aiomqtt


async def listen():
    async with aiomqtt.Client("test.mosquitto.org") as client:
        async with client.messages() as messages:
            await client.subscribe("humidity/#")
            async for message in messages:
                print(message.payload)


async def main():
    try:
        async with asyncio.timeout(5):
            await listen()
    # Ignore the resulting TimeoutError
    except asyncio.TimeoutError:
        pass


asyncio.run(main())
```

For everything from Python 3.10 and before, you can basically do the same thing, only a bit more verbose:

```python
import asyncio
import asyncio_mqtt as aiomqtt


async def listen():
    async with aiomqtt.Client("test.mosquitto.org") as client:
        async with client.messages() as messages:
            await client.subscribe("humidity/#")
            async for message in messages:
                print(message.payload)


async def main():
    loop = asyncio.get_event_loop()
    # Listen for mqtt messages in an (unawaited) asyncio task
    task = loop.create_task(listen())
    # Do something else for a while
    await asyncio.sleep(5)
    # Cancel the task
    task.cancel()
    # Wait for the task to be cancelled
    try:
        await task
    except asyncio.CancelledError:
        pass


asyncio.run(main())
```

Let me know if that helps!

**Comment by frederikaalund** [comment]
Hi Abbazs, thanks for opening this issue. Let me have a look. :)

Try to have a look at [`asyncio.timeout`](https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout).

---

Got ninja'd by empicano. 😅 We agree on the second option!

**Comment by empicano** [comment]
I guess we can close this then. Again, great question! 👍 

If anyone has questions left or feels that something is missing/unclear/wrong in [the documentation I added about this](https://sbtinstruments.github.io/asyncio-mqtt/stop-listening.html), additional comments are very welcome, feedback helps improve asyncio-mqtt!
