### ISSUE TITLE
Provide information about message instead of only the payload in unfiltered_messages

### ISSUE THREAD

**Issue by MBradbury** [sbtinstruments/asyncio-mqtt#2]
When using `unfiltered_messages` to receive all MQTT messages it would be useful if information about the message was provided instead of just the payload. For example, the `topic` field of the message at minimum would be useful.

This could be achieved by passing `msg` to `messages.put_nowait` in [`_cb_and_generator`](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L136) instead of `msg.payload`. The downside is that this exposes an instance of a class from mqtt.paho.

**Comment by frederikaalund** [comment]
Thanks for taking interest in the API. I'm open to changes. Let's have a look.

> When using unfiltered_messages to receive all MQTT messages it would be useful if information about the message was provided instead of just the payload. For example, the topic field of the message at minimum would be useful.

Sounds reasonable. This way, asyncio-mqtt feels more like a wrapper around paho-mqtt, which is the intent.

> This could be achieved by passing msg to messages.put_nowait in _cb_and_generator instead of msg.payload

Yup, it is indeed a simple change in the implementation. I like that.

> The downside is that this exposes an instance of a class from mqtt.paho.

Specifically, the [MQTTMessage](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L355) class. Said class is simple and well-defined. I have no problem with exposing it directly. This follows the "asyncio-mqtt is merely a wrapper around paho-mqtt" argument.

Of course, this is a breaking change but I vote for it in these early stages of the API.

Thanks again. Do you want to make the pull request or should I just do the change?

**Comment by MBradbury** [comment]
I'm happy to send a PR, thanks for the useful library!
