### ISSUE TITLE
docs/help: how to run with `uvicorn` alongside FastAPI

### ISSUE THREAD

**Issue by gegnew** [sbtinstruments/asyncio-mqtt#200]
The docs _should_ be enough for me to figure this out, but I haven't managed.

The [side-by-side with web frameworks](https://sbtinstruments.github.io/asyncio-mqtt/sharing-the-connection.html#side-by-side-with-web-frameworks) section in the docs shows how to set up a lifespan event with FastAPI. Good, fine.

Then [listening without blocking](https://sbtinstruments.github.io/asyncio-mqtt/listening-without-blocking.html#fire-and-forget) shows how to combine an async listener with a another generic async task. Also good.

I'm not really sure how to combine these in the context of FastAPI + uvicorn, where uvicorn wants to run the FastAPI app itself and handle the async loop internally. 

```python
# main.py
from fastapi import FastAPI
from contextlib import asynccontextmanager

mqtt_client = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global mqtt_client
    async with aiomqtt.Client('host') as client:
        mqtt_client = client
        yield

app = FastAPI(
    lifespan=lifespan,
)
```

then with the `uvicorn` CLI or:
```python
# run.py

from main import app

if __name__ == "__main__":
	uvicorn.run(app)
```

Awaiting `listen()` (from "listening without blocking") like this doesn't seem to work at all (just blocks on `server.serve()`)
```python
# run.py also
import uvicorn
import asyncio
from main import app, mqtt_client

async def main():
    config = uvicorn.Config(app)
        server = uvicorn.Server(config)
        await server.serve()
        await listen(mqtt_client)

if __name__ == "__main__":
    asyncio.run(main())
```

It's late and I'll take another crack at this tomorrow, but perhaps someone has a simple pattern that will make this sensible to me. Thanks!

**Comment by empicano** [comment]
I've updated the documentation with the more detailed example. If anybody comes up with a better solution to this, or if there are any questions remaining, please let me know 😊

**Comment by gegnew** [comment]
Hey guys thanks so much! I'll follow up here with a simple version of my final solution

**Comment by empicano** [comment]
Great! If you're stuck, let us know. Or post a minimal example of what doesn't work, always helps to know what people are struggling with to improve the docs 😋
