### ISSUE TITLE
requst for enhancement : paho.mqtt.proxy_set() - support

### ISSUE THREAD

**Issue by pichwo** [sbtinstruments/asyncio-mqtt#30]
REQUEST FOR ENHANCEMENT

if i am right, the followin function is presently unimplemented in asyncio-mqtt :

https://github.com/eclipse/paho.mqtt.python/blob/225ab3757f6818ba85eb80564948d1c787190cba/src/paho/mqtt/client.py#L875
( honestly, i wont pull because i think code-change is @maintainer ;-) )

asyncio-mqtt SHOULD make provisions to utilize paho.mqtt.client.proxy_set(**proxy_args)

there are no issues when using transport="websockets", since the websocket tcp-connection is proxy-unaware (hope i understand this right ;-), but e.g. connection via dynamic ssh-tunnels - by nature - need explicit support for connect via proxy.

thank your for enabling this "new" feature
w.

**Comment by frederikaalund** [comment]
Thanks for opening this issue. Let me have a look. :)

> asyncio-mqtt SHOULD make provisions to utilize paho.mqtt.client.proxy_set(**proxy_args)

You're absolutely right, `set_proxy` is not currently in asyncio-mqtt and, yes, we should include it.

> ( honestly, i wont pull because i think code-change is @maintainer ;-) )

It is a simple addition and you're welcome to make a pull request to add it. :+1: 
I suggest we follow the API design of the will feature. I.e.:
 * Create a `ProxySettings` class that holds all proxy arguments.
 * Add `proxy` as a keyword argument to the `Client`: `Client.__init__(self, ..., proxy: Optional[ProxySettings] = None)`

**Comment by Sohaib90** [comment]
I can look into this and create a pull request for this as well. Do you think I should go ahead with it?

**Comment by frederikaalund** [comment]
Excellent! I'd gladly review the PR on that. Good job on the other PR btw. 👍

**Comment by Sohaib90** [comment]
Thank you so much :)  Okay I will work on it and create a pull request.
