### ISSUE TITLE
error durring connection

### ISSUE THREAD

**Issue by vitalerter** [sbtinstruments/asyncio-mqtt#31]
Hi, i have error:
After few days that mqtt was connected well to broker suddenly i get an error:
```

  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read,
2021-01-07 08:52:16,574,base_events.py,base_events,default_exception_handler,ERROR,6,MainThread,Exception in callback Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py:291,
asyncio.base_futures.InvalidStateError: invalid state,
2021-01-07 08:52:16,574,client.py,client,_easy_log,ERROR,6,MainThread,Caught exception in on_connect: invalid state,
handle: <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py:291>,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run,
    self._context.run(self._callback, *self._args),
  File "/usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 292, in cb,
    client.loop_read(),
    rc = self._packet_read(),
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read,
    rc = self._packet_handle(),
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle,
    return self._handle_connack(),
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3030, in _handle_connack,
    self, self._userdata, flags_dict, result),
  File "/usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 242, in _on_connect,
    self._connected.set_result(rc),
future: <Future finished exception=MqttCodeError('Unexpected disconnect')>,
asyncio_mqtt.error.MqttCodeError: [code:1] Unexpected disconnect
```

**Comment by frederikaalund** [comment]
Thanks for opening this issue. :+1:  It does indeed look like a bug in asyncio-mqtt. I'll look into it. :)

Which version of asyncio-mqtt caused the crash?

**Comment by frederikaalund** [comment]
Can you show the code that produced this crash? It looks like `connect` was called twice, which isn't supported (you have to create a new `Client` instance).

**Comment by vitalerter** [comment]
> Thanks for opening this issue. 👍 It does indeed look like a bug in asyncio-mqtt. I'll look into it. :)
> 
> Which version of asyncio-mqtt caused the crash?

asyncio-mqtt-0.8.0

**Comment by vitalerter** [comment]
> Can you show the code that produced this crash? It looks like `connect` was called twice, which isn't supported (you have to create a new `Client` instance).

```
async with self.connect(broker) as client:
            _logging.info("connected to broker", extra={"data": {
                          "broker": broker,
                          "client_result": client._connected._result,
                          "client_state": client._connected._state,
                          }})
            self.clients[broker] = client
            async with client.unfiltered_messages() as messages:
                await client.subscribe("/topic")
                await client.subscribe("/topic2")
                async for message in messages:
                    await self.queue.put({"mqtt_msg": message})
```

```
async def start(self, brokers):
        try:
            _logging.info("Mqtt start")
            self.client_id = f'{str(get_mac())}{time.strftime("_%d-%m-%Y_%H-%M-%S_", time.gmtime())}'
            while True:
                try:
                    tasks = []
                    for broker in brokers:
                        tasks.append(asyncio.create_task(
                            self.messages_handler(broker)))
                    await asyncio.gather(*tasks)
                except MqttError as error:
                    _logging.error(f"Broker:{broker} not connected:{error}")
                    await asyncio.sleep(3)
        except asyncio.CancelledError:
            _logging.error('CancelledError!')
            pass
        finally:
            _logging.error('exit!')
```
```
def connect(self, broker):
        try:
            secure = self.config['mqtt'].get('secure', False)
            mqtt_username = self.config["mqtt"]["username"]
            mqtt_password = self.config["mqtt"]["password"]
            _logging.info("connecting to broker", extra={"data": {
                          "broker": broker,
                          "username": mqtt_username,
                          "password": mqtt_password,
                          "secure": secure}})
            if secure is True:
                return Client(hostname=broker, port=self.config["mqtt"]['ssl_port'],
                              username=mqtt_username,
                              password=mqtt_password,
                              client_id=self.client_id,
                              tls_context=self.set_contex(ca_certs=self.config["mqtt"]["certificate"]["ca_cert"],
                                                          certfile=self.config["mqtt"]["certificate"]["client_cert"],
                                                          keyfile=self.config["mqtt"]["certificate"]["client_key"],
                                                          cert_reqs=ssl.CERT_REQUIRED,
                                                          tls_version=ssl.PROTOCOL_TLSv1_2,
                                                          ciphers=None),
                              clean_session=True)
            else:
                return Client(hostname=broker, port=self.config["mqtt"]['tcp_port'],
                              username=mqtt_username,
                              password=mqtt_password,
                              client_id=self.client_id,
                              clean_session=True
                              )
        except MqttError as error:
            _logging.error(f"Broker:{broker} not connected:{error}")

```

**Comment by frederikaalund** [comment]
Thanks for posting your code. :+1:  From those snippets alone, I can't see anything wrong. So far so good.

From the stack trace, I can see that `Client._on_connect` is called twice. The design doesn't expect this, so you get the `InvalidStateError`. The question is then: Why does `Client._on_connect` get called twice?

I can sketch out two rough possibilities:
 1. The user accidentally calls `Client.connect` or `Client.__aenter__` twice.
 2. paho-mqtt calls the `on_connect` handler twice. Maybe because it receives `CONNACK` (`0x20`) twice.

I can't really tell if (1) is the case based on the snippets alone. I need access to the larger picture.

For (2), I don't really know. I've never head of this behaviour before but I guess there's always a first time. :) We could return early in the [`Client._on_connect` callback](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L240). This is similar to what we already do in [`Client._on_disconnect`](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L251). Do you want to make a pull request with this?

**Comment by vitalerter** [comment]
> Thanks for posting your code. 👍 From those snippets alone, I can't see anything wrong. So far so good.
> 
> From the stack trace, I can see that `Client._on_connect` is called twice. The design doesn't expect this, so you get the `InvalidStateError`. The question is then: Why does `Client._on_connect` get called twice?
> 
> I can sketch out two rough possibilities:
> 
> 1. The user accidentally calls `Client.connect` or `Client.__aenter__` twice.
> 2. paho-mqtt calls the `on_connect` handler twice. Maybe because it receives `CONNACK` (`0x20`) twice.
> 
> I can't really tell if (1) is the case based on the snippets alone. I need access to the larger picture.
> 
> For (2), I don't really know. I've never head of this behaviour before but I guess there's always a first time. :) We could return early in the [`Client._on_connect` callback](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L240). This is similar to what we already do in [`Client._on_disconnect`](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L251). Do you want to make a pull request with this?

1.Fix (2) can be fixed as you mention but I need Permission to pull request.
2. I looked at loges there are no other place that calls `Client.connect`

**Comment by frederikaalund** [comment]
> 1.Fix (2) can be fixed as you mention but I need Permission to pull request.

You can make a pull request without special permissions. :+1: See the "[Creating a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)" guide for details.
