### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by gilbertsmink** [sbtinstruments/asyncio-mqtt#35]
After some days of running I am receiving the "Broken pipe" error. This is currently not caught by asyncio-mqtt. Tbh this is too low level for me to understand. I expect it has something to do with an overflow of messages. It occurs at the same moment, I am not sure which is the cause and which is the effect, that the cpu, mem and swap are suddenly going crazy.

- Should this be something that my own script should catch and deal with?
- Should this be something that asyncio-mqtt should catch and deal with?
- or, is there another more preferred solution?

Trace:

```
evss_device_center.1.zaqg6zdkswua@evss24    | BrokenPipeError: [Errno 32] Broken pipe
evss_device_center.1.zaqg6zdkswua@evss24    | Exception in callback Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:291
evss_device_center.1.zaqg6zdkswua@evss24    | handle: <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:291>
evss_device_center.1.zaqg6zdkswua@evss24    | Traceback (most recent call last):
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
evss_device_center.1.zaqg6zdkswua@evss24    |     self._context.run(self._callback, *self._args)
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 292, in cb
evss_device_center.1.zaqg6zdkswua@evss24    |     client.loop_read()
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
evss_device_center.1.zaqg6zdkswua@evss24    |     rc = self._packet_read()
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
evss_device_center.1.zaqg6zdkswua@evss24    |     rc = self._packet_handle()
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
evss_device_center.1.zaqg6zdkswua@evss24    |     return self._handle_publish()
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3219, in _handle_publish
evss_device_center.1.zaqg6zdkswua@evss24    |     rc = self._send_puback(message.mid)
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2471, in _send_puback
evss_device_center.1.zaqg6zdkswua@evss24    |     return self._send_command_with_mid(PUBACK, mid, False)
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2580, in _send_command_with_mid
evss_device_center.1.zaqg6zdkswua@evss24    |     return self._packet_queue(command, packet, mid, 1)
evss_device_center.1.zaqg6zdkswua@evss24    |   File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2911, in _packet_queue
evss_device_center.1.zaqg6zdkswua@evss24    |     self._sockpairW.send(sockpair_data)

```

**Comment by frederikaalund** [comment]
Hi Gilbert. Thanks for the issue report. You raise some excellent questions. Let me have a look. :)

>  expect it has something to do with an overflow of messages.

Usually, programs raise [`BrokenPipeError`](https://docs.python.org/3/library/exceptions.html#BrokenPipeError) when the connection is closed or shut down for writing. The cause of `BrokenPipeError` can be anything from hardware failure to a temporary hiccup in network traffic.

> Should this be something that my own script should catch and deal with?

I personally vote "yes" to this question. It's up to the user to deal with general errors whether they are out-of-memory, hardware failures, or, as in this case, connection errors.

You'll have to catch and deal with `BrokenPipeError` in user code. I think I better change the "Advanced use" example code to read:

```python
        try:
            await advanced_example()
        # Catch both general-purpose connection errors and MQTT-specific errors.
        # Depending on your use case, you may want to add, e.g., `MemoryError` or
        # `OSError` to this list. Maybe even use the general-purpose `Exception` if
        # this is the main entry point to your application.
        except (ConnectionError, MqttError) as error:
            print(f'Error "{error}". Reconnecting in {reconnect_interval} seconds.')
        finally:
            await asyncio.sleep(reconnect_interval)
```

Note that `BrokenPipeError` is a subclass of `ConnectionError`.

Would something like the above work for you?

> Should this be something that asyncio-mqtt should catch and deal with?

I personally vote "no" to this question. Not even the underlying paho-mqtt library catches and deals with this. asyncio-mqtt is just a wrapper around paho-mqtt. I think it's most idiomatic to follow their line of thought and simply propagate `ConnectionError`s to the user.

We (asyncio-mqtt) should inform the user about these potential `ConnectionError`s. We failed in this regard so far (hence this issue). Going forward, I think the updated "Advanced use" example code (see above) solves this.

~Frederik

**Comment by gilbertsmink** [comment]
Thanks Frederik for the detailed and fast response. Extremely helpful!
I think this should work. I will check the details tomorrow and see to implement and test it. Will let you know how it goes, but will have to wait 1-2 weeks.

**Comment by gilbertsmink** [comment]
Hi Frederik,

Unfortunally , the error is not caught. Can it have something to do that the error is thrown inside a event loop task?

`
    async def start(self, will=None, on_connect=None, on_disconnect=None, reconnect_interval=5):
        # Run the advanced_example indefinitely. Reconnect automatically
        # if the connection is lost.
        self.log.info('Start mqtt worker, trying to connect..')
        while True:
            try:
                await self.connect_and_run(will, on_connect)
            except Exception as ex:
                if isinstance(ex, MqttError):
                    self.log.error("MQTT error")
                elif isinstance(ex, ConnectionError):
                    self.log.error("MQTT connection error")
                else:
                    self.log.error(f'Unknown exception: {ex}')
                self.log.error(traceback.format_exc())
                self.log.error(f'Trying to reconnect with a {reconnect_interval}s interval')
            finally:
                if on_disconnect is not None and self._connected:
                    on_disconnect()
                self._connected = False
                await asyncio.sleep(reconnect_interval)

    async def cancel_tasks(self, tasks):
        self.log.warning('Canceling mqtt worker tasks')
        for task in tasks:
            if task.done():
                continue
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass

    async def connect_and_run(self, will, on_connect):
        # Let's create a stack to help us manage them using a contect manager.
        async with AsyncExitStack() as stack:
            # Keep track of the asyncio tasks that we create, so that
            # we can cancel them on exit
            tasks = set()
            stack.push_async_callback(self.cancel_tasks, tasks)

            # Connect to the MQTT broker
            self.mqtt_client = AsyncioMqttClient(
                self.mqtt_client_settings.hostname,
                port=self.mqtt_client_settings.port,
                client_id=self.mqtt_client_settings.mqtt_client_id,
                username=self.mqtt_client_settings.username,
                password=self.mqtt_client_settings.password,
                will=will
                #logger=logger.create('ASYNCIO_MQTT_CLIENT')
            )
            
            await stack.enter_async_context(self.mqtt_client)
            self._connected = True
            if on_connect is not None:
                on_connect()
            self.log.info("Connected!")

            # Handle all messages that matches the filter
            for message_topic, message_handler in self.filtered_topic_handlers.items():
                self.log.info(f'Filtering message on topic : {message_topic}')
                manager = self.mqtt_client.filtered_messages(message_topic)
                messages = await stack.enter_async_context(manager)
                tasks.add(asyncio.create_task(self.delegate_filtered_messages(messages, message_handler)))

            # Messages that doesn't match a filter will get logged here
            self.log.info('Logging unfiltered messages')
            messages = await stack.enter_async_context(self.mqtt_client.unfiltered_messages())
            tasks.add(asyncio.create_task(self.log_unfiltered_messages(messages)))

            # Subscribe to topic(s)
            # Note that we subscribe *after* starting the message
            # loggers. Otherwise, we may miss retained messages.
            self.log.info('Subscribing to all topics: `#`')
            await self.subscribe("#", qos=1)

            self.log.info(f'Starting to publish queued mqtt messages')
            tasks.add(asyncio.create_task(self.publish_queued_messages(self.mqtt_queue)))

            # Wait for everything to complete (or fail due to, e.g., network
            # errors)
            await asyncio.gather(*tasks)
`

**Comment by frederikaalund** [comment]
Hi Gilbert. Thanks for the follow-up. :+1: Let me have a look. :)

You're absolutely right. The first time around I failed to see that this error occurs inside a [callback](https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L298). Currently, asyncio-mqtt fails to forward this error to the user.

I think that we need to change the callback to something like:
```python
def cb():
    try:
        client.loop_read()
    except Exception as exc:
        self._disconnected.set_exception(exc)
```

Same goes for the `loop_write` callback.

This way, the error propagates to the user and triggers the reconnect logic.

**Comment by gilbertsmink** [comment]
Ok, seems I was on the right path. I will try to see if I can implement, test and then  push the fix

**Comment by gilbertsmink** [comment]
Ok, fix looks stable after over a week of monitoring

Created pull request
https://github.com/sbtinstruments/asyncio-mqtt/pull/51

**Comment by gilbertsmink** [comment]
Is it possible to create a new release?

**Comment by frederikaalund** [comment]
Let me see if I can find some time to make a release in the weekend. :) I takes a little while to update the changelog.

**Comment by gilbertsmink** [comment]
any sight on doing the new release?

**Comment by frederikaalund** [comment]
Sorry about the long delay with this. I just updated the changelog and bumped the version to 0.9.0.

I have some difficulties with PyPI authentication at the moment. I created a support ticket and currently wait for someone to address it.

**Comment by frederikaalund** [comment]
New version (0.9.0) is now live on PyPI. :+1: 

Thanks again for your contribution to asyncio-mqtt. Sorry about the long delay before the release. :)
