### ISSUE TITLE
asyncio.get_event_loop().add_reader() doesn't work on windows out of the box

### ISSUE THREAD

**Issue by binary1230** [sbtinstruments/asyncio-mqtt#4]
Hey, this library rocks, thanks for writing it!

This is an upstream problem but, might be worth documenting the workaround somewhere, I am running this on Python 3.8.2 on Windows.

The API that asncio-mqtt uses calls ```asyncio.get_event_loop().add_reader()```

On windows, the default event_loop doesn't support ```add_reader()``` and throws an NotYetImplemented exception.

There's some other discussion in other projects like https://github.com/tornadoweb/tornado/issues/2608#issuecomment-619524992 about adding this as a workaround:

```
if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

It might be worth just having that code snippet documented somewhere for windows users of asyncio-mqtt

**Comment by frederikaalund** [comment]
Thanks for taking your time to document this behaviour and make me aware of it.

Indeed, it is an upstream issue so we are not able to fix it directly. I think it is a good idea to simply document this behaviour in lieu of a proper fix. This way, Windows users have a chance to avoid this apparently common issue with the `ProactorEventLoop`. I don't think that we should force a specific event loop implemention on our Windows users. Let them keep their choice of event loop and simply raise awareness of the issue instead.

I suggest that we add a "Note for Windows Users" section to the Readme.md file that explains this issue and the possible work-arounds. Maybe mention both `SelectorEventLoop` and `uvloop` just to give our users some choice. How does that sound to you?

Do you want to make a pull request or should I just go ahead and implement the change?

**Comment by binary1230** [comment]
Sure yeah I think a note with a suggested workaround is totally fine. just
gives a breadcrumb for people to make their own decisions after that

I'd say go ahead and document as you see fit, and thanks for taking the
time to read this. Library is working great with that change

**Comment by frederikaalund** [comment]
Great! :) I'll go ahead and document the behaviour when I have the time.

Thanks for reporting the issue. Please let me know if you encounter more strange behaviour like this.

**Comment by qorinator** [comment]
I had the same issue. Took me a while to get to this point because the error thrown from on_socket_open doesn't really show what type of error is thrown. 

It only says:
Caught exception in on_socket_open:
