### ISSUE TITLE
Cannot set the keepalive time

### ISSUE THREAD

**Issue by 0x0a11c0de** [sbtinstruments/asyncio-mqtt#45]
The paho client allows you to set the keepalive time. The asyncio-mqtt client does not. That is a pretty important parameter for controlling how much automatic communication happens with the mqtt server, and also for controlling when the server sends out the LWT.

**Comment by frederikaalund** [comment]
Hi there. Thanks for raising this issue. Let me have a look. :)

You're completely right. We don't expose paho-mqtt's `keepalive` parameter yet. I welcome you to add it via a PR if you want. 👍 It should be relatively straight-forward.

**Comment by jjlawren** [comment]
Looks like this was resolved with #56?

**Comment by frederikaalund** [comment]
It was indeed. Thanks for making me aware of this. :+1:
