### ISSUE TITLE
client._on_connect exception rc type error

### ISSUE THREAD

**Issue by jschlyter** [sbtinstruments/asyncio-mqtt#58]
It seems that https://github.com/sbtinstruments/asyncio-mqtt/blob/master/asyncio_mqtt/client.py#L387 may yield an error as `rc` is `paho.mqtt.reasoncodes.ReasonCodes` and not an integer?

    asyncio-mqtt==0.9.0
    paho-mqtt==1.5.1

**Comment by frederikaalund** [comment]
Hi Jakob, thanks for raising this issue. Let me have a look. :)

I think you're right. The following is an [excerpt from paho-mqtt](https://github.com/eclipse/paho.mqtt.python/blame/master/src/paho/mqtt/client.py#L1867):

```python
    def on_connect(self, func):
        """ Define the connect callback implementation.
        Expected signature for MQTT v3.1 and v3.1.1 is:
            connect_callback(client, userdata, flags, rc, properties=None)
        and for MQTT v5.0:
            connect_callback(client, userdata, flags, reasonCode, properties)
        client:     the client instance for this callback
        userdata:   the private user data as set in Client() or userdata_set()
        flags:      response flags sent by the broker
        rc:         the connection result
        reasonCode: the MQTT v5.0 reason code: an instance of the ReasonCode class.
                    ReasonCode may be compared to interger.
```

The connect callback gets:
 * an `int` for MQTT v3.1 and V3.1.1
 * a `ReasonCode` for MQTT v5.0

We should update the types to reflect this. Do you want to submit a pull request?

Note that [`ReasonCode` is comparable to `int`](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/reasoncodes.py#L175).

**Comment by jschlyter** [comment]
And thanks for keeping me honest - never report a bug without a PR is a golden rule! :-)
