### ISSUE TITLE
Reconnect support

### ISSUE THREAD

**Issue by longedok** [sbtinstruments/asyncio-mqtt#6]
Is there a way to handle lost connections to the broker in asyncio-mqtt? It seems like paho-mqtt implements automatic reconnection in its `loop_forever` function, for example, but I wasn't able to figure out how can I do a similar thing in asyncio-mqtt.

As a hacky solution, I tried awaiting the `_disconnected` future, and re-creating the Client instance, but this didn't work either, as the re-created client just hangs if the broker isn't available.

Bellow is the example code of trying to re-connect by creating a new client. To force a connection error, I stop and then restart my local mqtt broker.

```python
import asyncio
from contextlib import AsyncExitStack
from asyncio_mqtt import MqttError, Client

def get_stack_and_client():
    return AsyncExitStack(), Client("127.0.0.1")

async def reconnect_example():
    stack, client = get_stack_and_client()
    await stack.enter_async_context(client)
    print("connected")

    try:
        await client._disconnected  # killing broker here
    except MqttError as exc:
        print(f"disconnected {exc}")  # I get a "[code:1] Could not disconnect" error here

        try:
            await stack.aclose()
        except Exception as exc:
            print(f"closing 1st stack: {exc}")  # "[code:1] Could not disconnect" again

        for attempt in range(3):
            print(f"reconnecting attempt #{attempt}")
            stack, client = get_stack_and_client()
            await stack.enter_async_context(client)  # the code just hangs on this line, without even raising ConnectinRefused
            print("connected")

    await asyncio.sleep(10)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(reconnect_example())
    loop.close()

```

**Comment by frederikaalund** [comment]
Thanks for reporting this issue.

I've pushed a new commit to the master branch that improves the reconnection flow.

Can you try the following code and see if works for you?

```python
import asyncio
from contextlib import AsyncExitStack, asynccontextmanager
from random import randrange
from asyncio_mqtt import Client, MqttError


async def do_stuff():
    # We 💛 context managers. Let's create a stack to help
    # us manage them.
    async with AsyncExitStack() as stack:
        # Cancel tasks on exit
        tasks = set()
        @stack.push_async_callback
        async def _cancel_tasks():
            nonlocal tasks
            for task in tasks:
                task.cancel()
                try:
                    await task
                except asyncio.CancelledError:
                    pass

        # Connect to the MQTT broker
        client = Client("localhost")
        await stack.enter_async_context(client)

        # You can create any number of topic filters
        topic_filters = (
            "floors/+/humidity",
            "floors/rooftop/#"
            # 👉 Try to add more filters!
        )
        for topic_filter in topic_filters:
            # Log all messages that matches the filter
            manager = client.filtered_messages(topic_filter)
            messages = await stack.enter_async_context(manager)
            template = f'[topic_filter="{topic_filter}"] {{}}'
            task = asyncio.create_task(log_messages(messages, template))
            tasks.add(task)

        # Messages that doesn't match a filter will get logged here
        messages = await stack.enter_async_context(client.unfiltered_messages())
        task = asyncio.create_task(log_messages(messages, "[unfiltered] {}"))
        tasks.add(task)

        # Subscribe to topic(s)
        # 🤔 Note that we subscribe *after* starting the message
        # loggers. Otherwise, we may miss retained messages.
        await client.subscribe("floors/#")

        # Publish a random value to each of these topics
        topics = (
            "floors/basement/humidity",
            "floors/rooftop/humidity",
            "floors/rooftop/illuminance",
            # 👉 Try to add more topics!
        )
        while True:
            for topic in topics:
                message = randrange(100)
                print(f'[topic="{topic}"] Publishing message={message}')
                await client.publish(topic, message, qos=1)
                await asyncio.sleep(2)


async def log_messages(messages, template):
    async for message in messages:
        print(template.format(message.payload.decode()))


async def main():
    reconnect_interval = 3
    while True:
        try:
            await do_stuff()
        except MqttError as error:
            print(f'Error "{error}". Reconnecting in {reconnect_interval} seconds.')
            await asyncio.sleep(reconnect_interval)


asyncio.run(main())

```

**Comment by longedok** [comment]
Thanks a lot! I'm now able to re-connect after the connection is lost. I still need a way to detect losing connection in the middle of consuming messages, but I guess I can work around this using my `await client._disconnected` trick, or by subclassing and overriding the Client's `_on_disconnected` method somehow.

It would be ideal if the Client class could handle losing connection and re-connecting internally, with a way to notify user code that the connection was lost, but I understand that this will probably require significant development effort.

Bellow is a rough example of how I intend to implement re-connections in my code:
```python
import asyncio
from contextlib import AsyncExitStack

from asyncio_mqtt import MqttError, Client


async def start_consumer():
    stack, client = AsyncExitStack(), Client("127.0.0.1")
    await stack.enter_async_context(client)
    print("connected to the broker")

    tasks = set()

    @stack.push_async_callback
    async def _cancel_tasks():
        nonlocal tasks
        print("cancelling tasks")
        for task in tasks:
            task.cancel()
            try:
                await task
                print(f"{task} successfully cancelled")
            except asyncio.CancelledError:
                print(f"{task} cancellation error")

    manager = client.filtered_messages("s/+/result")
    messages = await stack.enter_async_context(manager)
    await client.subscribe("s/#")
    print("subscribed")
    task = asyncio.create_task(consume(messages))
    tasks.add(task)

    monitoring_task = asyncio.create_task(monitor_client(client))

    await monitoring_task
    await stack.aclose()


async def consume(messages):
    async for message in messages:
        print(f"Message received: {message}")


async def monitor_client(client):
    try:
        await client._disconnected
    except MqttError as exc:
        print(f"Monitor task detected disconnect: {exc}")


async def main():
    reconnect_interval = 3

    while True:
        try:
            await start_consumer()
            print("Reconnecting due to lost connection...")
        except MqttError as error:
            print(f'Error "{error}". Reconnecting in {reconnect_interval} seconds.')
        await asyncio.sleep(reconnect_interval)


asyncio.run(main())
```

**Comment by frederikaalund** [comment]
> Thanks a lot! I'm now able to re-connect after the connection is lost.

Glad to hear that it worked. :)

> I still need a way to detect losing connection in the middle of consuming messages, [...]

Ah, now I get it. I haven't tested with only a consumer and no producer. Let me see what I can do.

> It would be ideal if the Client class could handle losing connection and re-connecting internally, with a way to notify user code that the connection was lost, but I understand that this will probably require significant development effort.

Let's take it one step at a time. :) I can see that paho-mqtt's [loop_forever](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L1744) indeed automatically reconnects. They can do this easily, since the user code should do the subscription in the `on_connect` callback. From paho-mqtt's "[Getting started](https://github.com/eclipse/paho.mqtt.python/blob/master/README.rst#getting-started)":
```
# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))

    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    client.subscribe("$SYS/#")
```
In async-mqtt, we currently don't have a place in which "the user code should do the subscription". I personally think that this is a good thing as it doesn't restrict the user code. We could provide a convenience API for the common case of automatically resubscribing on reconnection. Do you have any suggestions for this API?

**Comment by longedok** [comment]
I don't have a lot of experience with asyncio and async code in general, not sure what would be a good general approach to handle this or if there're any good async utilities for this (I first learned about AsyncExitStack by using this library).

For my use case I don't mind re-subscribing from a single place, be it a callback or some other sort of notification on lost connection. It would also be nice if there's an option to handle reconnections transparently on publish (by providing a parameter in Client or having a separate ReconnectingClient class). 

For subscriptions I'm really not sure. Probably there needs to be a separate utility for keeping track of subscriptions that should be restored, or maybe it just makes sense to restore all subscriptions.

**Comment by frederikaalund** [comment]
> I don't have a lot of experience with asyncio and async code in general, not sure what would be a good general approach to handle this or if there're any good async utilities for this (I first learned about AsyncExitStack by using this library).

Glad that you could learn something from asyncio-mqtt. :)

> For my use case I don't mind re-subscribing from a single place, be it a callback or some other sort of notification on lost connection. It would also be nice if there's an option to handle reconnections transparently on publish (by providing a parameter in Client or having a separate ReconnectingClient class).

All of these are great ideas for the `publish`-part of the API. I'll keep them in mind. :)

> For subscriptions I'm really not sure. Probably there needs to be a separate utility for keeping track of subscriptions that should be restored, or maybe it just makes sense to restore all subscriptions.

When I find some time for it, I'll see if I can sketch up some possible solutions in a separate issue.

---

I'm still looking into the issue with disconnection while iterating the messages. I have a local branch with a work-in-progress fix that I made yesterday night but I ran out of time to finish it. I'll keep you posted.

**Comment by longedok** [comment]
Sounds great!

**Comment by frederikaalund** [comment]
I've pushed the changes to the master branch. Can you please check and see if it solves your use case? :)

I've also updated the "Advanced Example" in the README.md file with reconnection logic. You can refer to that to see how reconnection can be done. Try to comment out the "publish task", so that only the "subscribe" tasks remain. Even with just subscribers, it should still detect a broken connection.

Let me know if you have any questions.

**Comment by longedok** [comment]
I adapted the example to my project, and tested it in the subscriber-only case - and it's indeed able to detect broken connection and re-connect. Once again, thanks a lot!

Do you have any plans to publish an updated version of the lib to pypi anytime soon?

**Comment by frederikaalund** [comment]
> I adapted the example to my project, and tested it in the subscriber-only case - and it's indeed able to detect broken connection and re-connect. Once again, thanks a lot!

That's great to hear. :) I consider this issue solved then.

> Do you have any plans to publish an updated version of the lib to pypi anytime soon?

Yes, I'll make a release right away. I was waiting for your feedback.

**Comment by frederikaalund** [comment]
I couldn't make the release from work. Some problem with `twine`. I'll try again from home.

**Comment by frederikaalund** [comment]
Version 0.5.0 is on PyPI now.
