### ISSUE TITLE
Request for a patch release 0.9.1

### ISSUE THREAD

**Issue by resingm** [sbtinstruments/asyncio-mqtt#61]
Unsuccessful authentication to the broker leads to an invalid error message in `asyncio-mqtt`. The issue was addressed in #58  and fixed with PR #59.
I'd really like to see the change on PyPI.org under a patch release 0.9.1.

By any chance, are there plans to release a patch release anytime soon?

**Comment by frederikaalund** [comment]
Thanks for creating this issue. Let me have a look. :)

Sure thing, I'll make a release right away. :+1:

**Comment by frederikaalund** [comment]
I just released v0.9.1 on PyPI. Thanks again for your request. :+1:

**Comment by resingm** [comment]
Thanks for responding so quickly! Awesome!
