### ISSUE TITLE
Very slow publishing data more 100 MB.

### ISSUE THREAD

**Issue by xydan83** [sbtinstruments/asyncio-mqtt#70]
Hello again! I noticed one thing, when I try to transfer a file larger than 100MB, it takes a very long time when publishing, it can take 3-5 minutes. If I use TLS, then 2-3 times longer. Moreover, the subscriber receives this file instantly. Any idea why this might be the case? Could it be the small size of the TCP allocated buffer?

![image](https://user-images.githubusercontent.com/86729310/124878832-3713ba80-dfd5-11eb-9334-38d7a491ffd2.png)

P.s. I`m using Ubuntu 20.04.1

**Comment by frederikaalund** [comment]
Hi again. :) Thanks for raising this issue. Let me have a look.

I've never tested with packets of that size to be honest. The specification let's the messages be as large as 256 MiB but people usually send much smaller messages (well under 1 MiB).

In any case, let's rule out some potential bottlenecks first.

 1. What kind of transfer speeds do you get with alternative MQTT clients on the same network?
 2. Is the server and client on the same machine? (that would be good for network traffic)
 3. Is the machine a recent desktop/laptop computer? (and not, say, a Raspberry Pi or something)

I'm particularly interested in (1). It'll give us a rough estimate of what to expect in therms of transfer speeds of large messages.

> Any idea why this might be the case? Could it be the small size of the TCP allocated buffer?

That's a good guess. :+1: As a quick test, you can try to increase this to `20480`. Let me know what you figure out. :)

**Comment by frederikaalund** [comment]
By the way, the only reason that `SNDBUF` is `2048` is because I got that setting from the [`loop_asyncio.py` example in paho.mqtt](https://github.com/eclipse/paho.mqtt.python/blob/0cc8581aa11dbea31364619c1bec6f920dbfec3e/examples/loop_asyncio.py#L89). I don't know why they change it from the default.

**Comment by frederikaalund** [comment]
The `SNDBUF` default value on my system is `212992`! That's 104 times bigger than `2048`. Maybe we shouldn't change it from the default.

**Comment by xydan83** [comment]
I tried increasing the buffer and it really increased the transfer rate. Now my file with TLS enabled was transferred in less than 3 minutes. Previously, I generally went into a timeout.

![image](https://user-images.githubusercontent.com/86729310/124911527-84a01f80-dff5-11eb-929b-81704b730d93.png)

Can we move the buffer setting to the __init__?

And, my answers:
1.For example, through a mosquito_pub - instantly transmitted (though without TLS)
![image](https://user-images.githubusercontent.com/86729310/124912620-da28fc00-dff6-11eb-8cbc-93c33c6c2c83.png)
2. Yes, this is a localhost,
3. This is a desktop (x86)

**Comment by xydan83** [comment]
Another local test. I increased the buffer to 1 MB and the file was transferred (with TLS) to the broker - instantly.

![image](https://user-images.githubusercontent.com/86729310/124914044-8a4b3480-dff8-11eb-9848-db0f6b8ebed5.png)

**Comment by xydan83** [comment]
Can we move the buffer setting to the __init__?

**Comment by frederikaalund** [comment]
Thanks for doing the tests. :+1: Seems to me like the best approach is to simply remove the setting altogether and just use the default value. It was a mistake on my part to change this setting to begin with (I just copied the line from the paho.mqtt example code). :sweat: 

Do you want to do a PR? :)

**Comment by xydan83** [comment]
I can remove the **_set_client_socket_defaults** method from the module **client.py** and remove string `_set_client_socket_defaults(client_socket)` from the **connect** method.

I'm also very interested in why the **Paho** creators at changing the buffer parameter in the example. Very strange. O_o

**Comment by frederikaalund** [comment]
You're right, we can remove the entire `_set_client_socket_defaults` method altogether. Nice. :+1: I'm ready to merge in a PR. :)

> I'm also very interested in why the Paho creators at changing the buffer parameter in the example. Very strange. O_o

To be fair, the usual MQTT message size is very small. It's a reasonable optimization if you can make such assumptions. Still, it shouldn't go into the example code like that. Very strange indeed.

**Comment by xydan83** [comment]
Yes, guys could make a comment on this.
Ok, but if this is an optimization, is it definitely worth removing this method? Maybe it's better to set the size to **__init__** ? And set 2048 by default.

It is true that usually big data is not transmitted via mqtt, but there is an exception)

**Comment by frederikaalund** [comment]
Good point. :) If you want to, you can add a keyword argument to `Client.__init__` like `socket_options`, that is a list/dict/something with various socket options. This way, our users can supply any socket option that they want to use. :+1: 

In any case, I think it's a good idea to remove the hard-coded `2048` value that we currently have.

**Comment by xydan83** [comment]
OK. I will do an MR a little later)

**Comment by xydan83** [comment]
Hi)
I opened the MR) Look please)

**Comment by frederikaalund** [comment]
I merged your pull request. Thanks again! :)
