### ISSUE TITLE
Disconnect after a certain number of messages were published

### ISSUE THREAD

**Issue by stijn-devriendt** [sbtinstruments/asyncio-mqtt#75]
I'd like to bring the following issue to your attention:
https://github.com/eclipse/paho.mqtt.python/issues/563?_pjax=%23js-repo-pjax-container#issuecomment-901803191
I added a comment explaining the issue and how asyncio-mqtt is involved.

As far as I know, the root cause is in paho-mqtt, but is exacerbated by how asyncio-mqtt uses paho-mqtt.
I'm not sure there's much you can do about it in asyncio-mqtt, except for calling `loop()` instead.
However, I believe that is not a full solution since the sockpair will still get out of sync.

Most likely when paho-mqtt is fixed, you'll want to bump the required version.

**Comment by frederikaalund** [comment]
Hi Stijn, thanks for bringing this issue to our attention. :+1:  Like you mention yourself, this is something that paho-mqtt must fix. We can't really do that much from the asyncio-mqtt side, unfortunately. In any case, it's good to have the issue tracked here as well. :) Let us know if there are any major updates on it.

**Comment by stijn-devriendt** [comment]
Hi Frederik, As you can read on the paho-mqtt issue, their 1.6.x branch contains a fix. The maintainer is aiming for a release around the end of September, so I guess that might be a good time to revisit the paho-mqtt project for an update.

**Comment by stijn-devriendt** [comment]
The dependency of paho-mqtt has been updated already for another issue.
I guess this one can be closed?

**Comment by frederikaalund** [comment]
You're right. Thanks for following up on this issue. :+1:
