### ISSUE TITLE
Username and no password

### ISSUE THREAD

**Issue by Shikoruma** [sbtinstruments/asyncio-mqtt#88]
This condition did'nt work when username is set and password is None. Password can be optional. It is in paho-mqtt.

https://github.com/sbtinstruments/asyncio-mqtt/blob/5d8a0f1dbdee35e3def307587176ec896abc2848/asyncio_mqtt/client.py#L151

I was stuck half an hour to undertand this library needed password="" to work. Otherwise the username is not set and you get a connection refused.

**Comment by frederikaalund** [comment]
Hi Shikoruma, thanks for opening this issue. Let me have a look. :)

Good catch! :+1: Indeed, paho allows you to set the username and leave the password blank. This doesn't currently work in asyncio-mqtt. You already found the culprit and it looks like it's an easy fix. Do you want to submit a pull request? :)
