### ISSUE TITLE
implementation of will-messages

### ISSUE THREAD

**Issue by vomov** [sbtinstruments/asyncio-mqtt#9]
I've not found any implementation of LWT or 'will' messages in the readme or the code. Is this correct? If so; is this on the roadmap?

**Comment by frederikaalund** [comment]
Thanks for raising this issue.

The `set_will` function simply isn't forwarded to paho-mqtt. It's an oversight. :) It should be straight-forward to implement this. Do you want to make a pull request or should I just go ahead and add `set_will`?

**Comment by vomov** [comment]
I'm unsure how the asyncio will impact the LWT functionality, so I think it'd be better you implement it.
After all: I'm only learning to work with asyncio using your wrapper ;)

**Comment by frederikaalund** [comment]
You can now set the will like this:

```python
from asyncio_mqtt import Client, Will

will = Will("my/topic", "This is the payload")

async with Client("test.mosquitto.org", will=will) as client:
    async with client.filtered_messages("floors/+/humidity") as messages:
        await client.subscribe("floors/#")
        async for message in messages:
            print(message.payload.decode())
```

**Comment by frederikaalund** [comment]
Again, thanks for reporting this issue. Let me know if you're having further trouble with asyncio-mqtt. :)
