### ISSUE TITLE
The advanced example is possibly buggy

### ISSUE THREAD

**Issue by steverpalmer** [sbtinstruments/asyncio-mqtt#92]
Thank you for asyncio-mqtt; I've used it many of my home IoT applications.
I noticed one (pedantic) thing the the advance example that you might consider changing...
The function cancel_task contains the code:

        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

Unfortunately, it is possible that the CancelledError exception arrives between `task.cancel` call and the try block.  It is better practice to do:

        try:
            task.cancel()
            await task
        except asyncio.CancelledError:
            pass

**Comment by frederikaalund** [comment]
Hi Steve. Thanks for opening this issue. :+1: Let me have a look. :)

Glad to hear that you found a good use for asyncio-mqtt. 

As for the issue itself: Nice find! The fix that you propose looks good to me. Do you want to submit a pull request?

~Frederik
