### ISSUE TITLE
 client.filtered_message blocking async loop

### ISSUE THREAD

**Issue by CrispyCrafter** [sbtinstruments/asyncio-mqtt#97]
I am trying to integrate asyncio-mqtt into a async web-framework. 
The obvious choice would be to run the client in a separate thread, however that complicates client heartbeats and the utility of publishing to topics via API.

In my case I'm using `aiohttp` for it's lightweight simplicity. 
It seems the `AsyncIterator` created by `filtered_messages` via `_cb_and_generator` is blocking the rest of the loop from executing. 

Is there a way to avoid the `AsyncIterator` from being blocking ? 

Here is an example where the `aiohttp` webserver never instantiates fully due to `async for`.
```
import asyncio
from contextlib import AsyncExitStack

from aiohttp import web
from asyncio_mqtt import Client, MqttError


async def uplink_consumer(messages):
    async for message in messages:
        print(f"Processing {message}")


class MQTTConsumer:
    async def run(self, app, consumer=uplink_consumer, topic=None, topic_filters=None):
        topic = "floors/#"
        topic_filters = ["floors/bed_room/humidity"]

        async with AsyncExitStack() as stack:
            tasks = set()
            stack.push_async_callback(self.cancel_tasks, tasks)

            # Connect to the MQTT broker
            client = Client("test.mosquitto.org")
            await stack.enter_async_context(client)
            
            for topic_filter in topic_filters:
                # Log all messages that matches the filter
                manager = client.filtered_messages(topic_filter, queue_maxsize=1)
                messages = await stack.enter_async_context(manager)
                template = f'[topic_filter="{topic_filter}"] {{}}'
                task = asyncio.create_task(consumer(messages))
                tasks.add(task)

            await client.subscribe(topic)
            await asyncio.gather(*tasks)


    async def cancel_tasks(self, tasks, app=None):
        for task in tasks:
            if task.done():
                continue
            try:
                task.cancel()
                await task
            except asyncio.CancelledError:
                pass

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

def create_app():
    app = web.Application()
    app.add_routes(
        [web.get('/', handle),
        web.get('/{name}', handle)]
    )
    consumer = MQTTConsumer()
    app.on_startup.append(consumer.run)

    return app

if __name__ == "__main__":
    app = create_app()
    web.run_app(app,host="0.0.0.0", port=8000)            
 ```

**Comment by frederikaalund** [comment]
Hi Bernard. Thanks for opening this issue. Let me have a look.

> It seems the AsyncIterator created by filtered_messages via _cb_and_generator is blocking the rest of the loop from executing.

Your `MQTTConsumer.run` method never returns. That's why your code never advances further. Technically speaking, this doesn't "block the event loop".

Try something like this instead:

```python
consumer_task = asyncio.create_task(consumer.run)
```

This way, the task doesn't block.

Also, this is not an issue for the asyncio-mqtt issue tracker. It's about asyncio and async/await in general. Try the discussions or stackoverflow.com. :+1: 

~Frederik

**Comment by gab933** [comment]
Hi, I have the same issue.
I tried your solution, but still code blocks.
Any news on it?
Thank you

**Comment by frederikaalund** [comment]
Please post the code that you tried. :) Otherwise, it's difficult for me to asses whether you "tried my solution" or not. 👍

**Comment by gab933** [comment]
async def connect():
		# Let's create a stack to help us manage them.
		async with AsyncExitStack() as stack:
			# Keep track of the asyncio tasks that we create, so that we can cancel them on exit
			tasks = set()
			stack.push_async_callback(cancel_tasks, tasks)

			# Connect to the MQTT broker
			client = Client(hostname="broker", username="user", password="pwd")
			await stack.enter_async_context(client)

			# Topic filters
			topic_filters = (
				"prova/#"
			)
			for topic_filter in topic_filters:
				# Log all messages that matches the filter
				manager = client.filtered_messages(topic_filter)
				messages = await stack.enter_async_context(manager)
				template = f'[topic_filter="{topic_filter}"] {{}}'
				task = asyncio.create_task(log_messages(messages, template))
				#tasks.add(task)

			# Subscribe to topic(s)
			await client.subscribe("prova/#")

			# Wait for everything to complete (or fail due to, e.g., network errors)
			print("Before")
			#await asyncio.gather(*tasks)
			await task
			print("After")



	async def log_messages(messages, template):
		async for message in messages:
			print(template.format(message.payload.decode()))
			print(message.topic)


	async def cancel_tasks(tasks):
		for task in tasks:
			if task.done():
				continue
			try:
				task.cancel()
				await task
			except asyncio.CancelledError:
				pass


	async def main():
		# Run the advanced_example indefinitely. Reconnect automatically if the connection is lost.
		reconnect_interval = 3  # [seconds]
		while True:
		  try:
			  await connect()
		  except MqttError as error:
			  print(f'Error "{error}". Reconnecting in {reconnect_interval} seconds.')
		  finally:
			  await asyncio.sleep(reconnect_interval)


  `asyncio.run(main())`


This is more or less the test code you posted on ReadMe.
At the end of connect() function I attempt to print "Before" and "After".
"Before" is printed, instead "After" is not printed.
I tried with both:

`tasks.add(task)`
`await asyncio.gather(*tasks)`

(as the original example, here commented), and

`await task`

to start the coroutine without using asyncio.gather.
In both cases "After" is not printed, by confirming the same blocking issue encountered by CrispyCrafter.
Thank you for quick reply

**Comment by frederikaalund** [comment]
Thanks for posting the code. 👍 

> `await task`
>
> to start the coroutine without using asyncio.gather.
> In both cases "After" is not printed, by confirming the same blocking issue encountered by CrispyCrafter.

This is the expected behaviour. `await task` does not return before the task is done (which is never).

In any case, this question is about how async/await works in general and *not* about asyncio-mqtt. I only support the latter here. For general async/await questions you need to get answers elsewhere. Try stackoverflow.com for instance. :)
